#nullable enable
// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
// =====================================================================

using System.Text.Json;
using System.Text.Json.Serialization;

namespace SagaOrchestrator.Core.Utilities;

/// <summary>
/// Provides System.Text.Json serialization extensions for saga identifiers generated by SagaIdGenerator.
/// </summary>
public static class SagaIdGeneratorJsonExtensions
{
    private static readonly JsonSerializerOptions _jsonSerializerOptions = new JsonSerializerOptions
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = false,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };

    /// <summary>
    /// Serializes a saga ID string to JSON.
    /// </summary>
    /// <param name="value">The saga ID string to serialize.</param>
    /// <param name="indented">Whether to format the JSON with indentation for readability.</param>
    /// <returns>A JSON string representation of the saga ID.</returns>
    public static string ToJson(this string value, bool indented = false)
    {
        if (value == null)
        {
            return "{}";
        }

        var options = indented
            ? new JsonSerializerOptions(_jsonSerializerOptions)
            {
                WriteIndented = true
            }
            : _jsonSerializerOptions;

        return JsonSerializer.Serialize(new { SagaId = value }, options);
    }

    /// <summary>
    /// Deserializes a JSON string to a saga ID.
    /// </summary>
    /// <param name="json">The JSON string to deserialize.</param>
    /// <returns>A saga ID string, or null if deserialization fails.</returns>
    public static string? FromJson(string json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            return null;
        }

        try
        {
            var result = JsonSerializer.Deserialize<SagaIdModel>(json, _jsonSerializerOptions);
            return result?.SagaId;
        }
        catch (JsonException)
        {
            return null;
        }
    }

    /// <summary>
    /// Attempts to deserialize a JSON string to a saga ID.
    /// </summary>
    /// <param name="json">The JSON string to deserialize.</param>
    /// <param name="value">The deserialized saga ID string, or null if deserialization fails.</param>
    /// <returns>True if deserialization succeeds; otherwise, false.</returns>
    public static bool TryFromJson(string json, out string? value)
    {
        value = null;

        if (string.IsNullOrWhiteSpace(json))
        {
            return false;
        }

        try
        {
            var result = JsonSerializer.Deserialize<SagaIdModel>(json, _jsonSerializerOptions);
            value = result?.SagaId;
            return true;
        }
        catch (JsonException)
        {
            return false;
        }
    }

    private sealed class SagaIdModel
    {
        public string? SagaId { get; set; }
    }
}